Name = "Scaleway"
Description = ''''''
URL = "https://developers.scaleway.com/"
Code = "scaleway"
Since = "v3.3.0"

Example = ''''''

[Configuration]
  [Configuration.Credentials]
    SCALEWAY_API_TOKEN = "API token"
  [Configuration.Additional]
    SCALEWAY_BASE_URL = "API endpoint URL"
    SCALEWAY_API_VERSION = "API version"
    SCALEWAY_POLLING_INTERVAL = "Time between DNS propagation check"
    SCALEWAY_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    SCALEWAY_TTL = "The TTL of the TXT record used for the DNS challenge"

[Links]
  API = "https://developers.scaleway.com/en/products/domain/api/"
